# A human-readable name for your workflow
name: Run Neuro Bot

# Ensures only ONE instance of this workflow runs at a time.
# If a new run is triggered by the schedule, it will automatically cancel the old one.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# --- TRIGGERS ---
# Defines WHEN the workflow will run.
on:
  # Allows you to manually start the workflow from the Actions tab.
  workflow_dispatch:

  # Automatically starts the workflow every 6 hours to keep it running 24/7.
  schedule:
    - cron: '0 */6 * * *'

  # Automatically starts when you push new code.
  push:
    branches: [ "main" ]

# --- JOBS ---
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y # Install any missing dependencies for Chrome

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy selenium requests fake-useragent psutil "urllib3<2"

      - name: Run Neuro Bot Script
        env:
          FIREBASE_GMAIL_USER: ${{ secrets.FIREBASE_GMAIL_USER }}
          FIREBASE_GMAIL_APP_PASSWORD: ${{ secrets.FIREBASE_GMAIL_APP_PASSWORD }}
        run: python "Final version minions works gemeini buildt.py"
